spring:
  cloud:
    config:
      allow-override: true
      overrideNone: true
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888
