version: '2.1'
services:
  config:
    build: config
    ports:
      - 8888:8888
    restart: always

  registry:
    build: registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761

  accounts:
    build: accounts
    restart: always
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy
    ports:
      - 2222:2222

  webserver:
    build: webserver
    restart: always
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy
    ports:
      - 3333:3333

  product-catalog:
    build: product-catalog
    restart: always
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy
    ports:
      - 4444:4444

  cart-service:
    build: cart-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy
    ports:
      - 5555:5555

  gateway:
    build: gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy
    ports:
      - 80:7777