spring:
  cloud:
    config:
      allow-override: true
      overrideNone: true

logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'